---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: security-postgres-cnpg-helm-values
    files:
      - values.yaml=helm-values.yaml
configurations:
  - kustomizeconfig.yaml
