---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./radarr-db-auth-secret.yaml
  - ./radarr-deploy.yaml
  - ./radarr-env.yaml
  - ./radarr-ingressroute.yaml
  - ./radarr-pvc.yaml
  - ./radarr-svc.yaml
