---
environment:
  MEILI_EXPERIMENTAL_DUMPLESS_UPGRADE: "true"
persistence:
  enabled: true
  storageClassName: "local-path"
  existingClaim: meilisearch-data-pvc
auth:
  existingMasterKeySecret: meilisearch-secrets
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch
