---
persistence:
  enabled: true
  storageClassName: "local-path"
  existingClaim: meilisearch-data-pvc
auth:
  existingMasterKeySecret: meilisearch-secrets
podSecurityContext:
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch
