---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cnpg-system.yaml
  - edge.yaml
  - media.yaml
  - monitoring.yaml
  - observability.yaml
  - security.yaml
