---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cloudnative-pg/ks.yaml
  # - ./default-postgres/ks.yaml
  - ./default-postgres-cnpg/ks.yaml
  # - ./influxdb/ks.yaml
  - ./media-postgres-cnpg/ks.yaml
  - ./redis/ks.yaml
  # - ./security-postgres/ks.yaml
  - ./security-postgres-cnpg/ks.yaml
